spring:
  application:
    name: discovery-service
  profiles:
    active: development
  config:
    import: "optional:configserver:http://root:admin@localhost:8888"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

