spring:
  application:
    name: cart-service
  profiles:
    active: development
  config:
    import: "optional:configserver:http://root:admin@localhost:8888"

#logging:
#  level:
#    org:
#      springframework:
#        cloud: DEBUG
